version: '3.8'
services:
  apache:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./public_html:/var/www/html

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - ./db/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "888:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    depends_on:
      - apache
      - mysql

volumes:
  mysql-data: